import 'package:organik/models/shop.dart';

class Dummy {
  // static List<ProductCategory> categories = [
  //   ProductCategory("1", "name", "assets/images/eggs.svg"),
  //   ProductCategory("2", "name", "assets/images/eggs.svg"),
  //   ProductCategory("3", "name", "assets/images/eggs.svg"),
  //   ProductCategory("4", "name", "assets/images/eggs.svg"),
  //   ProductCategory("5", "name", "assets/images/eggs.svg"),
  //   ProductCategory("6", "name", "assets/images/eggs.svg"),
  //   ProductCategory("7", "name", "assets/images/eggs.svg"),
  //   ProductCategory("8", "name", "assets/images/eggs.svg"),
  //   ProductCategory("9", "name", "assets/images/eggs.svg"),
  //   ProductCategory("10", "name", "assets/images/eggs.svg"),
  // ];

  List<Shop> shops = [
    Shop(
        id: "",
        name: "",
        bio: "",
        rate: 0,
        logo: "",
        website: "",
        phoneNumber: "",
        address: "",
        workingHours: null,
        categories: null,
        geoPoint: null),
    Shop(
        id: "",
        name: "",
        bio: "",
        rate: 0,
        logo: "",
        website: "",
        phoneNumber: "",
        address: "",
        workingHours: null,
        categories: null,
        geoPoint: null),
    Shop(
        id: "",
        name: "",
        bio: "",
        rate: 0,
        logo: "",
        website: "",
        phoneNumber: "",
        address: "",
        workingHours: null,
        categories: null,
        geoPoint: null),
    Shop(
        id: "",
        name: "",
        bio: "",
        rate: 0,
        logo: "",
        website: "",
        phoneNumber: "",
        address: "",
        workingHours: null,
        categories: null,
        geoPoint: null),
    Shop(
        id: "",
        name: "",
        bio: "",
        rate: 0,
        logo: "",
        website: "",
        phoneNumber: "",
        address: "",
        workingHours: null,
        categories: null,
        geoPoint: null),
    Shop(
        id: "",
        name: "",
        bio: "",
        rate: 0,
        logo: "",
        website: "",
        phoneNumber: "",
        address: "",
        workingHours: null,
        categories: null,
        geoPoint: null),
    Shop(
        id: "",
        name: "",
        bio: "",
        rate: 0,
        logo: "",
        website: "",
        phoneNumber: "",
        address: "",
        workingHours: null,
        categories: null,
        geoPoint: null),
    Shop(
        id: "",
        name: "",
        bio: "",
        rate: 0,
        logo: "",
        website: "",
        phoneNumber: "",
        address: "",
        workingHours: null,
        categories: null,
        geoPoint: null),
    Shop(
        id: "",
        name: "",
        bio: "",
        rate: 0,
        logo: "",
        website: "",
        phoneNumber: "",
        address: "",
        workingHours: null,
        categories: null,
        geoPoint: null),
    Shop(
        id: "",
        name: "",
        bio: "",
        rate: 0,
        logo: "",
        website: "",
        phoneNumber: "",
        address: "",
        workingHours: null,
        categories: null,
        geoPoint: null),
  ];
}
